# Generated by Django 3.1.7 on 2021-03-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
