# Generated by Django 3.1.7 on 2021-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210323_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.CharField(default='Django', max_length=60),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
