# Generated by Django 3.1.7 on 2021-03-23 05:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210323_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 5, 21, 13, 685718, tzinfo=utc), verbose_name='date published'),
        ),
    ]
