# Generated by Django 3.1.7 on 2021-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(upload_to='user_images/', verbose_name='image'),
        ),
    ]
