# Generated by Django 3.1.7 on 2021-04-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210426_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='user',
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='username',
            field=models.CharField(default='AnonymousUser', max_length=150, verbose_name='username'),
        ),
    ]
