# Generated by Django 3.1.7 on 2021-04-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210426_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='image'),
        ),
    ]
