# Generated by Django 3.1.7 on 2021-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210426_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Number Of Dislikes'),
        ),
    ]
